/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import control.Cargador;
import control.Controlador;
import control.TablaRenderer;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import proyecto.Sismo;
import proyecto.TFalla;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
/**
 *
 * @author Dayron
 */
public class Interfaz extends javax.swing.JFrame {
    
    private Controlador control = new Controlador();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameTabla = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregarSismo = new javax.swing.JButton();
        frameHistograma = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistograma = new javax.swing.JTable();
        frameAgregarSismo = new javax.swing.JFrame();
        lblSismo = new javax.swing.JLabel();
        selectorFechaAgregarSismo = new javax.swing.JSpinner();
        lblFecha1 = new javax.swing.JLabel();
        selectorMagnitud = new javax.swing.JSpinner();
        lblSismo1 = new javax.swing.JLabel();
        selectorProfundidad = new javax.swing.JSpinner();
        lblSismo2 = new javax.swing.JLabel();
        txtLocalizacion = new javax.swing.JTextField();
        lblSismo3 = new javax.swing.JLabel();
        spnSelectorOrigen = new javax.swing.JSpinner();
        spnSelectorProvincia = new javax.swing.JSpinner();
        lblSismo4 = new javax.swing.JLabel();
        lblSismo5 = new javax.swing.JLabel();
        lblSismo6 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtLatitud = new javax.swing.JTextField();
        btnActualizarSismo = new javax.swing.JButton();
        lblErrorLongitud = new javax.swing.JLabel();
        lblErrorLatitud1 = new javax.swing.JLabel();
        lblSismoAgregado = new javax.swing.JLabel();
        frameSismoPorFecha = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSelectorFecha = new javax.swing.JLabel();
        btnSelectorFecha = new javax.swing.JButton();
        selectorFecha2 = new javax.swing.JSpinner();
        selectorFecha1 = new javax.swing.JSpinner();
        frameModificarSismo = new javax.swing.JFrame();
        lblSismo7 = new javax.swing.JLabel();
        selectorFechaAgregarSismo1 = new javax.swing.JSpinner();
        lblFecha2 = new javax.swing.JLabel();
        selectorMagnitud1 = new javax.swing.JSpinner();
        lblSismo8 = new javax.swing.JLabel();
        selectorProfundidad1 = new javax.swing.JSpinner();
        lblSismo9 = new javax.swing.JLabel();
        txtLocalizacion1 = new javax.swing.JTextField();
        lblSismo10 = new javax.swing.JLabel();
        spnSelectorOrigen1 = new javax.swing.JSpinner();
        spnSelectorProvincia1 = new javax.swing.JSpinner();
        lblSismo11 = new javax.swing.JLabel();
        lblSismo12 = new javax.swing.JLabel();
        lblSismo13 = new javax.swing.JLabel();
        txtLongitud1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtLatitud1 = new javax.swing.JTextField();
        btnActualizarSismo1 = new javax.swing.JButton();
        lblErrorLongitud1 = new javax.swing.JLabel();
        lblErrorLatitud2 = new javax.swing.JLabel();
        lblSismoAgregado1 = new javax.swing.JLabel();
        frameTablaPorMagnitud = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPorMagnitd = new javax.swing.JTable();
        btnMostrarSismos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSismosPorFecha = new javax.swing.JButton();
        btnSismosPorMagnitud = new javax.swing.JButton();

        frameTabla.setMinimumSize(new java.awt.Dimension(1341, 754));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusCycleRoot(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnAgregarSismo.setText("Agregar un nuevo sismo");
        btnAgregarSismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSismoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameTablaLayout = new javax.swing.GroupLayout(frameTabla.getContentPane());
        frameTabla.getContentPane().setLayout(frameTablaLayout);
        frameTablaLayout.setHorizontalGroup(
            frameTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTablaLayout.createSequentialGroup()
                .addGroup(frameTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameTablaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAgregarSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameTablaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        frameTablaLayout.setVerticalGroup(
            frameTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTablaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAgregarSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        frameTabla.getAccessibleContext().setAccessibleParent(this);

        frameHistograma.setMinimumSize(new java.awt.Dimension(542, 235));

        tblHistograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistograma);

        javax.swing.GroupLayout frameHistogramaLayout = new javax.swing.GroupLayout(frameHistograma.getContentPane());
        frameHistograma.getContentPane().setLayout(frameHistogramaLayout);
        frameHistogramaLayout.setHorizontalGroup(
            frameHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameHistogramaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        frameHistogramaLayout.setVerticalGroup(
            frameHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameHistogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        frameAgregarSismo.setMinimumSize(new java.awt.Dimension(523, 713));

        lblSismo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo.setText("Magnitud");

        selectorFechaAgregarSismo.setModel(new javax.swing.SpinnerDateModel());

        lblFecha1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFecha1.setText("Fecha y hora:");

        selectorMagnitud.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 10.0d, 0.1d));

        lblSismo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo1.setText("Profundidad");

        selectorProfundidad.setModel(new javax.swing.SpinnerNumberModel(1.0d, null, null, 1.0d));

        lblSismo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo2.setText("Localizacion");

        txtLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalizacionActionPerformed(evt);
            }
        });

        lblSismo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo3.setText("Tipo de origen:");

        lblSismo4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo4.setText("Latitud:");

        lblSismo5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo5.setText("Provincia:");

        lblSismo6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo6.setText("Longitud:");

        txtLongitud.setText("-");
        txtLongitud.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });

        txtLatitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudActionPerformed(evt);
            }
        });

        btnActualizarSismo.setText("Agregar Sismo");
        btnActualizarSismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSismoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameAgregarSismoLayout = new javax.swing.GroupLayout(frameAgregarSismo.getContentPane());
        frameAgregarSismo.getContentPane().setLayout(frameAgregarSismoLayout);
        frameAgregarSismoLayout.setHorizontalGroup(
            frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorFechaAgregarSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo3)
                            .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSismo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(lblSismo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selectorProfundidad)
                                    .addComponent(selectorMagnitud, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                            .addComponent(spnSelectorOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSelectorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                                .addComponent(txtLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorLatitud1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblSismo6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                                .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnActualizarSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lblSismoAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        frameAgregarSismoLayout.setVerticalGroup(
            frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorFechaAgregarSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorMagnitud, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSismo1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(selectorProfundidad, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSismo2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSismo3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnSelectorOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSismo5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnSelectorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSismo4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorLatitud1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                        .addComponent(lblSismo6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblErrorLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnActualizarSismo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSismoAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(frameAgregarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameAgregarSismoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        frameSismoPorFecha.setMinimumSize(new java.awt.Dimension(414, 366));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese un rango de fecha:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("desde:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("hasta:");

        lblSelectorFecha.setForeground(new java.awt.Color(255, 0, 0));
        lblSelectorFecha.setToolTipText("");

        btnSelectorFecha.setText("Mostrar");
        btnSelectorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectorFechaActionPerformed(evt);
            }
        });

        selectorFecha2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1631167140000L), new java.util.Date(1631167140000L), null, java.util.Calendar.DAY_OF_MONTH));

        selectorFecha1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1631167140000L), new java.util.Date(1631080800000L), null, java.util.Calendar.DAY_OF_MONTH));

        javax.swing.GroupLayout frameSismoPorFechaLayout = new javax.swing.GroupLayout(frameSismoPorFecha.getContentPane());
        frameSismoPorFecha.getContentPane().setLayout(frameSismoPorFechaLayout);
        frameSismoPorFechaLayout.setHorizontalGroup(
            frameSismoPorFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSismoPorFechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frameSismoPorFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameSismoPorFechaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSelectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSismoPorFechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
            .addGroup(frameSismoPorFechaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblSelectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        frameSismoPorFechaLayout.setVerticalGroup(
            frameSismoPorFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSismoPorFechaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSelectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        frameModificarSismo.setMinimumSize(new java.awt.Dimension(523, 713));

        lblSismo7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo7.setText("Magnitud");

        selectorFechaAgregarSismo1.setModel(new javax.swing.SpinnerDateModel());

        lblFecha2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFecha2.setText("Fecha y hora:");

        selectorMagnitud1.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 10.0d, 0.1d));

        lblSismo8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo8.setText("Profundidad");

        selectorProfundidad1.setModel(new javax.swing.SpinnerNumberModel(1.0d, null, null, 1.0d));

        lblSismo9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo9.setText("Localizacion");

        txtLocalizacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalizacion1ActionPerformed(evt);
            }
        });

        lblSismo10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo10.setText("Tipo de origen:");

        lblSismo11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo11.setText("Latitud:");

        lblSismo12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo12.setText("Provincia:");

        lblSismo13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSismo13.setText("Longitud:");

        txtLongitud1.setText("-");
        txtLongitud1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLongitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitud1ActionPerformed(evt);
            }
        });

        txtLatitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitud1ActionPerformed(evt);
            }
        });

        btnActualizarSismo1.setText("Agregar Sismo");
        btnActualizarSismo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSismo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameModificarSismoLayout = new javax.swing.GroupLayout(frameModificarSismo.getContentPane());
        frameModificarSismo.getContentPane().setLayout(frameModificarSismoLayout);
        frameModificarSismoLayout.setHorizontalGroup(
            frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameModificarSismoLayout.createSequentialGroup()
                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameModificarSismoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorFechaAgregarSismo1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameModificarSismoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLocalizacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo10)
                            .addGroup(frameModificarSismoLayout.createSequentialGroup()
                                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSismo8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(lblSismo7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selectorProfundidad1)
                                    .addComponent(selectorMagnitud1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                            .addComponent(spnSelectorOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSelectorProvincia1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSismo11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameModificarSismoLayout.createSequentialGroup()
                                .addComponent(txtLatitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorLatitud2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblSismo13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameModificarSismoLayout.createSequentialGroup()
                                .addComponent(txtLongitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorLongitud1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(frameModificarSismoLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnActualizarSismo1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameModificarSismoLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lblSismoAgregado1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameModificarSismoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        frameModificarSismoLayout.setVerticalGroup(
            frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameModificarSismoLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorFechaAgregarSismo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSismo7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorMagnitud1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSismo8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(selectorProfundidad1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSismo9, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocalizacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSismo10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnSelectorOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSismo12, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnSelectorProvincia1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSismo11, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLatitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorLatitud2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameModificarSismoLayout.createSequentialGroup()
                        .addComponent(lblSismo13, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLongitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameModificarSismoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblErrorLongitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnActualizarSismo1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSismoAgregado1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(frameModificarSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameModificarSismoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        frameTablaPorMagnitud.setMinimumSize(new java.awt.Dimension(1200, 537));

        tablaPorMagnitd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPorMagnitd.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tablaPorMagnitd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaPorMagnitd.setFocusCycleRoot(true);
        tablaPorMagnitd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPorMagnitdMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaPorMagnitd);

        javax.swing.GroupLayout frameTablaPorMagnitudLayout = new javax.swing.GroupLayout(frameTablaPorMagnitud.getContentPane());
        frameTablaPorMagnitud.getContentPane().setLayout(frameTablaPorMagnitudLayout);
        frameTablaPorMagnitudLayout.setHorizontalGroup(
            frameTablaPorMagnitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTablaPorMagnitudLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        frameTablaPorMagnitudLayout.setVerticalGroup(
            frameTablaPorMagnitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTablaPorMagnitudLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMostrarSismos.setText("Mostrar sismos");
        btnMostrarSismos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSismosActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar sismos por mes del año");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar simos por tipo de origen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar sismos por provincia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSismosPorFecha.setText("Mostrar sismo por un rango de fecha");
        btnSismosPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismosPorFechaActionPerformed(evt);
            }
        });

        btnSismosPorMagnitud.setText("Mostrar sismos por clasificacion de magnitud");
        btnSismosPorMagnitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismosPorMagnitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarSismos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSismosPorFecha)
                        .addGap(18, 18, 18)
                        .addComponent(btnSismosPorMagnitud)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarSismos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSismosPorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSismosPorMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Funcion del boton que abre la tabla con los sismos
     * @param evt 
     */
    private void btnMostrarSismosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSismosActionPerformed
        // TODO add your handling code here:
        frameTabla.setVisible(true);
        actualizarTabla();
        
    }//GEN-LAST:event_btnMostrarSismosActionPerformed
    private void actualizarTabla(){
        
        jTable1.setModel(control.tablaDeSismos());
        jTable1.setDefaultRenderer(Object.class, new TablaRenderer());
        for (int i = 0; i < jTable1.getRowCount(); i++){
            jTable1.setValueAt(control.crearBoton("ver mapa"), i, 9);
            JButton boton = control.crearBoton("modificar");
            boton.setName("modificar");
            jTable1.setValueAt(boton, i, 10);
        } 
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(250);
        jTable1.setRowHeight(20);
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            
        ChartPanel Panel = new ChartPanel(control.graficoSismosPorMes());
        JFrame Ventana = new JFrame("JFreeChart");
        Ventana.getContentPane().add(Panel);
        Ventana.pack();
        Ventana.setVisible(true);
        Ventana.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        // Mostrar Grafico
        ChartFrame frame = new ChartFrame("JFreeChart", control.graficoSismosPorFalla());
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //JTable provincias = new JTable();
        ChartFrame frame = new ChartFrame("JFreeChart",control.graficoSismosPorProvincia());
      
        frame.pack();
        frame.setVisible(true);
        frameHistograma.setVisible(true);
        tblHistograma.setModel(control.tablaHistograma());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSismosPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismosPorFechaActionPerformed
        // TODO add your handling code here:
        
        frameSismoPorFecha.setVisible(true);
    }//GEN-LAST:event_btnSismosPorFechaActionPerformed

    private void btnSelectorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectorFechaActionPerformed
        // TODO add your handling code here:
        Date fecha1 = new Date();
        fecha1 = (Date) selectorFecha1.getValue();
        
        Date fecha2 = new Date();
        fecha2 = (Date) selectorFecha2.getValue();
        if (fecha2.before(fecha1)){
            lblSelectorFecha.setText(fecha2.toString());//"la segunda fecha no puede ser antes que la primera");
            return;
        }
        else{
            jTable1.setModel(control.sismosPorFecha(fecha1, fecha2));
            frameTabla.setVisible(true);
        }
        
    }//GEN-LAST:event_btnSelectorFechaActionPerformed

    private void btnAgregarSismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSismoActionPerformed
        // TODO add your handling code here:
        this.spnSelectorOrigen.setModel(control.selectorFallas());
        this.spnSelectorProvincia.setModel(control.selectorProvincias());
    
        this.frameAgregarSismo.setVisible(true);
    }//GEN-LAST:event_btnAgregarSismoActionPerformed

    private void txtLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacionActionPerformed

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtLongitudActionPerformed

    private void txtLatitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatitudActionPerformed

    private void btnActualizarSismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSismoActionPerformed
        // TODO add your handling code here:
        Date fecha = (Date)this.selectorFechaAgregarSismo.getValue();
        int hora = fecha.getHours();
        int minutos = fecha.getMinutes();
        String horas = String.valueOf(control.formatoMilitar(hora)) +":"+ String.valueOf(minutos)+":00"+control.ampm(hora);
        double magnitud = (double)this.selectorMagnitud.getValue();
        double profundidad = (double)this.selectorProfundidad.getValue();
        String localizacion = this.txtLocalizacion.getText();
        TFalla origen = (TFalla) this.spnSelectorOrigen.getValue();
        String provincia = (String) this.spnSelectorProvincia.getValue();
        double latitud = 0.0;
        boolean flag = true;
        try{
            latitud = Double.valueOf(this.txtLatitud.getText());
            this.lblErrorLatitud1.setText("");
            flag= flag & true;
        }
        catch(NumberFormatException e){
            this.lblErrorLatitud1.setText("Debe ingresar una latitud en formato decimal (double)");
            flag=false;
        }
        double longitud = 0.0;
        try{
            longitud = Double.valueOf(this.txtLongitud.getText());
            this.lblErrorLongitud.setText("");
            flag= flag & true;
        }
        catch(NumberFormatException e){
            this.lblErrorLongitud.setText("Debe ingresar una longitud en formato decimal (double) y negativa");
            flag= false;
        }
        if (flag == true){
            Sismo nuevoSismo = new Sismo(fecha,horas,magnitud,profundidad,localizacion,origen,provincia,latitud,longitud);
            if (control.agregarSismo(nuevoSismo)){
                this.lblSismoAgregado.setText("Sismo agregado");
                control.escribeExcel(nuevoSismo);
                try {
                    control.consultaCorreo(provincia, nuevoSismo);
                } catch (MessagingException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
                actualizarTabla();
            }
        }
        else
            this.lblSismoAgregado.setText("Sismo NO agregado");
    }//GEN-LAST:event_btnActualizarSismoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0){
            Object value = jTable1.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                
                if (boton.getText().equals("ver mapa")){
                    double latidud = control.getSismos().get(row).getLatitud();
                    double longitud = control.getSismos().get(row).getLongitud();
                    control.verMapa(latidud ,longitud);
                
                }
                else{
                    indexActual = row;
                    this.spnSelectorOrigen1.setModel(control.selectorFallas());
                    this.spnSelectorProvincia1.setModel(control.selectorProvincias());
                    this.frameModificarSismo.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked
    private int indexActual;
            
    private void txtLocalizacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacion1ActionPerformed

    private void txtLongitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud1ActionPerformed

    private void txtLatitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatitud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatitud1ActionPerformed

    private void btnActualizarSismo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSismo1ActionPerformed
        // TODO add your handling code here:
        Date fecha = (Date)this.selectorFechaAgregarSismo1.getValue();
        int hora = fecha.getHours();
        int minutos = fecha.getMinutes();
        String horas = String.valueOf(control.formatoMilitar(hora)) +":"+ String.valueOf(minutos)+":00"+control.ampm(hora);
        double magnitud = (double)this.selectorMagnitud1.getValue();
        double profundidad = (double)this.selectorProfundidad1.getValue();
        String localizacion = this.txtLocalizacion1.getText();
        TFalla origen = (TFalla) this.spnSelectorOrigen1.getValue();
        String provincia = (String) this.spnSelectorProvincia1.getValue();
        double latitud = 0.0;
        boolean flag = true;
        try{
            latitud = Double.valueOf(this.txtLatitud1.getText());
            this.lblErrorLatitud2.setText("");
            flag= flag & true;
        }
        catch(NumberFormatException e){
            this.lblErrorLatitud2.setText("Debe ingresar una latitud en formato decimal (double)");
            flag=false;
        }
        double longitud = 0.0;
        try{
            longitud = Double.valueOf(this.txtLongitud1.getText());
            this.lblErrorLongitud1.setText("");
            flag= flag & true;
        }
        catch(NumberFormatException e){
            this.lblErrorLongitud1.setText("Debe ingresar una longitud en formato decimal (double) y negativa");
            flag= false;
        }
        if (flag == true){
            Sismo nuevoSismo = new Sismo(fecha,horas,magnitud,profundidad,localizacion,origen,provincia,latitud,longitud);
            if (control.agregarSismo(nuevoSismo,indexActual)){
                this.lblSismoAgregado1.setText("Sismo agregado");
                control.escribeExcel(nuevoSismo);
                try {
                    control.consultaCorreo(provincia, nuevoSismo);
                } catch (MessagingException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.frameModificarSismo.setVisible(false);
                actualizarTabla();
            }
        }
        else
            this.lblSismoAgregado1.setText("Sismo NO agregado");
        
    }//GEN-LAST:event_btnActualizarSismo1ActionPerformed

    private void tablaPorMagnitdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPorMagnitdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPorMagnitdMouseClicked

    private void btnSismosPorMagnitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismosPorMagnitudActionPerformed
        // TODO add your handling code here:
        this.tablaPorMagnitd.setModel(control.tablaValorMagnitud());
        this.frameTablaPorMagnitud.setVisible(true);
    }//GEN-LAST:event_btnSismosPorMagnitudActionPerformed
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    JFreeChart grafica;
    //DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarSismo;
    private javax.swing.JButton btnActualizarSismo1;
    private javax.swing.JButton btnAgregarSismo;
    private javax.swing.JButton btnMostrarSismos;
    private javax.swing.JButton btnSelectorFecha;
    private javax.swing.JButton btnSismosPorFecha;
    private javax.swing.JButton btnSismosPorMagnitud;
    private javax.swing.JFrame frameAgregarSismo;
    private javax.swing.JFrame frameHistograma;
    private javax.swing.JFrame frameModificarSismo;
    private javax.swing.JFrame frameSismoPorFecha;
    private javax.swing.JFrame frameTabla;
    private javax.swing.JFrame frameTablaPorMagnitud;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblErrorLatitud1;
    private javax.swing.JLabel lblErrorLatitud2;
    private javax.swing.JLabel lblErrorLongitud;
    private javax.swing.JLabel lblErrorLongitud1;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblSelectorFecha;
    private javax.swing.JLabel lblSismo;
    private javax.swing.JLabel lblSismo1;
    private javax.swing.JLabel lblSismo10;
    private javax.swing.JLabel lblSismo11;
    private javax.swing.JLabel lblSismo12;
    private javax.swing.JLabel lblSismo13;
    private javax.swing.JLabel lblSismo2;
    private javax.swing.JLabel lblSismo3;
    private javax.swing.JLabel lblSismo4;
    private javax.swing.JLabel lblSismo5;
    private javax.swing.JLabel lblSismo6;
    private javax.swing.JLabel lblSismo7;
    private javax.swing.JLabel lblSismo8;
    private javax.swing.JLabel lblSismo9;
    private javax.swing.JLabel lblSismoAgregado;
    private javax.swing.JLabel lblSismoAgregado1;
    private javax.swing.JSpinner selectorFecha1;
    private javax.swing.JSpinner selectorFecha2;
    private javax.swing.JSpinner selectorFechaAgregarSismo;
    private javax.swing.JSpinner selectorFechaAgregarSismo1;
    private javax.swing.JSpinner selectorMagnitud;
    private javax.swing.JSpinner selectorMagnitud1;
    private javax.swing.JSpinner selectorProfundidad;
    private javax.swing.JSpinner selectorProfundidad1;
    private javax.swing.JSpinner spnSelectorOrigen;
    private javax.swing.JSpinner spnSelectorOrigen1;
    private javax.swing.JSpinner spnSelectorProvincia;
    private javax.swing.JSpinner spnSelectorProvincia1;
    private javax.swing.JTable tablaPorMagnitd;
    private javax.swing.JTable tblHistograma;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLatitud1;
    private javax.swing.JTextField txtLocalizacion;
    private javax.swing.JTextField txtLocalizacion1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtLongitud1;
    // End of variables declaration//GEN-END:variables
}
